services:
  - type: web
    name: medlens-ai
    runtime: python
    region: singapore
    plan: free
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn disease_prediction.api.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: true

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SUPABASE_DB_HOST
        value: aws-0-ap-southeast-2.pooler.supabase.com
      - key: SUPABASE_DB_PORT
        value: "6543"
      - key: SUPABASE_DB_USER
        value: postgres.qvupcpgoxdcfdqowwhls
      - key: SUPABASE_DB_PASSWORD
        value: Hiran@56151
      - key: SUPABASE_DB_NAME
        value: postgres
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_MODEL
        value: google/gemma-4-31b-it:free
      - key: OPENROUTER_SITE_URL
        fromService:
          type: web
          name: medlens-ai
          property: host
      - key: OPENROUTER_APP_NAME
        value: MEDLENS AI Health Assistant
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_FROM
        value: whatsapp:+14155238886
      - key: PATHOLOGY_SECRET_KEY
        generateValue: true
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: medlens-ai
          property: host
